"""empty message

Revision ID: 8a9479ab93ee
Revises: 37e31ddbf40c
Create Date: 2024-03-27 18:04:55.152417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9479ab93ee'
down_revision: Union[str, None] = '37e31ddbf40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('members_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'members_count')
    # ### end Alembic commands ###
